name: Destroy Staging Infrastructure

on:
  workflow_dispatch:  # Manual trigger in GitHub Actions

jobs:
  terraform-destroy:
    name: Terraform Destroy (Staging)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform Repository
        uses: actions/checkout@v4
        with:
          repository: jjoby12323/Angoor-JoinTask-Terraform
          ref: staging  # Ensure it checks out the correct branch

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Confirm Destroy Readiness
        run: terraform plan -destroy -out=tf-destroy.plan

      - name: Terraform Destroy
        run: terraform apply -auto-approve tf-destroy.plan
