name: Production Deployment

on:
  push:
    branches:
      - prod-*  # Triggers only for production branches

jobs:
  docker:
    name: Build and Push Docker Images (Production)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Django Repository
        uses: actions/checkout@v4
        with:
          repository: jjoby12323/Angoor-JoinTask-Django
          ref: ${{ github.ref_name }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set ECR Repositories
        run: |
          echo "ECR_DJANGO=762233750800.dkr.ecr.us-east-1.amazonaws.com/django-app-prod" >> $GITHUB_ENV
          echo "ECR_CELERY=762233750800.dkr.ecr.us-east-1.amazonaws.com/celery-worker-prod" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_DJANGO
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_CELERY

      - name: Build and Push Django Image
        run: |
          IMAGE_TAG=$(date +%s)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          docker build -t django-app:$IMAGE_TAG -f Dockerfile .
          docker tag django-app:$IMAGE_TAG $ECR_DJANGO:$IMAGE_TAG
          docker push $ECR_DJANGO:$